FORMAT: 1A
HOST: https://api.boxmeupapp.com

# Boxmeup API
Boxmeup is a web and mobile application to help users keep track of what they have in their containers and how to find items in specific containers.

## User [/users]

## Login [POST]

+ Request (application/json)

        {
            "email": "Email address",
            "password": "Password for authentication",
            "application": "Application name using this API"
        }

+ Response 200 (application/json)

        {
            "token": "1cd2b6edc30afc5e0e8084c83601506de69f53a3"
        }
